import { AcGeMathUtil } from '@mlightcad/geometry-engine'

import { acdbHostApplicationServices } from '../src/base'
import {
  AcDbBlockTableRecordFlag,
  AcDbDatabase
} from '../src/database'
import { AcDbNativeDxfConverter } from '../src/dxf'
import {
  AcDbBlockReference,
  AcDbCircle,
  AcDbEllipse,
  AcDbFace,
  AcDbLine,
  AcDbMText,
  AcDbPolyline,
  AcDbRay,
  AcDbRotatedDimension,
  AcDbSolid,
  AcDbSpline,
  AcDbTable,
  AcDbText,
  AcDbXline,
  AcDb3dSolid
} from '../src/entity'

describe('AcDbNativeDxfConverter', () => {
  it('streams HEADER, LAYER, and core entities into the database', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'HEADER',
      '9',
      '$ACADVER',
      '1',
      'AC1032',
      '9',
      '$INSUNITS',
      '70',
      '4',
      '9',
      '$HANDSEED',
      '5',
      'FF',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'TABLES',
      '0',
      'TABLE',
      '2',
      'LAYER',
      '0',
      'LAYER',
      '5',
      '10',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbLayerTableRecord',
      '2',
      'Walls',
      '70',
      '0',
      '62',
      '1',
      '6',
      'Continuous',
      '290',
      '1',
      '370',
      '-3',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      'LINE',
      '5',
      '1A',
      '100',
      'AcDbEntity',
      '8',
      'Walls',
      '100',
      'AcDbLine',
      '10',
      '1',
      '20',
      '2',
      '30',
      '0',
      '11',
      '10',
      '21',
      '20',
      '31',
      '0',
      '0',
      'CIRCLE',
      '5',
      '1B',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbCircle',
      '10',
      '5',
      '20',
      '5',
      '30',
      '0',
      '40',
      '3',
      '0',
      'LWPOLYLINE',
      '5',
      '1C',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbPolyline',
      '90',
      '3',
      '70',
      '1',
      '10',
      '0',
      '20',
      '0',
      '10',
      '10',
      '20',
      '0',
      '10',
      '10',
      '20',
      '5',
      '0',
      'TEXT',
      '5',
      '1D',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbText',
      '10',
      '1',
      '20',
      '1',
      '30',
      '0',
      '40',
      '2.5',
      '1',
      'Hello',
      '50',
      '90',
      '7',
      'Standard',
      '0',
      'INSERT',
      '5',
      '1E',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockReference',
      '2',
      'Door',
      '10',
      '100',
      '20',
      '200',
      '30',
      '0',
      '41',
      '2',
      '42',
      '2',
      '43',
      '1',
      '50',
      '45',
      '0',
      'RAY',
      '5',
      '1F',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbRay',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '1',
      '21',
      '0',
      '31',
      '0',
      '0',
      'XLINE',
      '5',
      '20',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbXline',
      '10',
      '5',
      '20',
      '5',
      '30',
      '0',
      '11',
      '0',
      '21',
      '1',
      '31',
      '0',
      '0',
      'ELLIPSE',
      '5',
      '21',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbEllipse',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '10',
      '21',
      '0',
      '31',
      '0',
      '40',
      '0.5',
      '41',
      '0',
      '42',
      '6.283185307179586',
      '0',
      'SOLID',
      '5',
      '22',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbTrace',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '1',
      '21',
      '0',
      '31',
      '0',
      '12',
      '1',
      '22',
      '1',
      '32',
      '0',
      '13',
      '0',
      '23',
      '1',
      '33',
      '0',
      '0',
      '3DFACE',
      '5',
      '23',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbFace',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '2',
      '21',
      '0',
      '31',
      '0',
      '12',
      '2',
      '22',
      '2',
      '32',
      '0',
      '13',
      '0',
      '23',
      '2',
      '33',
      '0',
      '70',
      '0',
      '0',
      'MTEXT',
      '5',
      '24',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbMText',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '40',
      '2',
      '41',
      '10',
      '1',
      'Hello\\PWorld',
      '7',
      'Standard',
      '71',
      '1',
      '0',
      'SPLINE',
      '5',
      '25',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbSpline',
      '70',
      '0',
      '71',
      '3',
      '72',
      '8',
      '73',
      '4',
      '40',
      '0',
      '40',
      '0',
      '40',
      '0',
      '40',
      '0',
      '40',
      '1',
      '40',
      '1',
      '40',
      '1',
      '40',
      '1',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '10',
      '1',
      '20',
      '1',
      '30',
      '0',
      '10',
      '2',
      '20',
      '0',
      '30',
      '0',
      '10',
      '3',
      '20',
      '1',
      '30',
      '0',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    expect(db.version.name).toBe('AC1032')
    expect(db.insunits).toBe(4)

    const walls = db.tables.layerTable.getAt('Walls')
    expect(walls).toBeDefined()
    expect(walls!.color.colorIndex).toBe(1)
    expect(walls!.linetype).toBe('Continuous')

    const entities = [...db.tables.blockTable.modelSpace.newIterator()]
    expect(entities).toHaveLength(12)

    expect(entities[0]).toBeInstanceOf(AcDbLine)
    const line = entities[0] as AcDbLine
    expect(line.layer).toBe('Walls')
    expect(line.startPoint).toMatchObject({ x: 1, y: 2, z: 0 })

    expect(entities[1]).toBeInstanceOf(AcDbCircle)
    expect((entities[1] as AcDbCircle).radius).toBe(3)

    expect(entities[2]).toBeInstanceOf(AcDbPolyline)
    const pline = entities[2] as AcDbPolyline
    expect(pline.closed).toBe(true)
    expect(pline.numberOfVertices).toBe(3)

    expect(entities[3]).toBeInstanceOf(AcDbText)
    const text = entities[3] as AcDbText
    expect(text.textString).toBe('Hello')
    expect(text.height).toBe(2.5)
    expect(text.rotation).toBeCloseTo(AcGeMathUtil.degToRad(90))

    expect(entities[4]).toBeInstanceOf(AcDbBlockReference)
    const insert = entities[4] as AcDbBlockReference
    expect(insert.blockName).toBe('Door')
    expect(insert.position).toMatchObject({ x: 100, y: 200, z: 0 })
    expect(insert.scaleFactors).toMatchObject({ x: 2, y: 2, z: 1 })
    expect(insert.rotation).toBeCloseTo(AcGeMathUtil.degToRad(45))

    expect(entities[5]).toBeInstanceOf(AcDbRay)
    expect((entities[5] as AcDbRay).unitDir).toMatchObject({ x: 1, y: 0, z: 0 })

    expect(entities[6]).toBeInstanceOf(AcDbXline)
    expect((entities[6] as AcDbXline).basePoint).toMatchObject({
      x: 5,
      y: 5,
      z: 0
    })

    expect(entities[7]).toBeInstanceOf(AcDbEllipse)
    const ellipse = entities[7] as AcDbEllipse
    expect(ellipse.majorAxisRadius).toBeCloseTo(10)
    expect(ellipse.minorAxisRadius).toBeCloseTo(5)

    expect(entities[8]).toBeInstanceOf(AcDbSolid)
    expect((entities[8] as AcDbSolid).getPointAt(2)).toMatchObject({
      x: 1,
      y: 1,
      z: 0
    })

    expect(entities[9]).toBeInstanceOf(AcDbFace)
    expect((entities[9] as AcDbFace).getVertexAt(1)).toMatchObject({
      x: 2,
      y: 0,
      z: 0
    })

    expect(entities[10]).toBeInstanceOf(AcDbMText)
    expect((entities[10] as AcDbMText).contents).toBe('Hello\\PWorld')
    expect((entities[10] as AcDbMText).height).toBe(2)

    expect(entities[11]).toBeInstanceOf(AcDbSpline)
  })

  it('streams CLASSES, TABLES metadata, and BLOCKS into the database', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'CLASSES',
      '0',
      'CLASS',
      '1',
      'ACDBDICTIONARYWDFLT',
      '2',
      'AcDbDictionaryWithDefault',
      '3',
      'ObjectDBX Classes',
      '90',
      '0',
      '91',
      '1',
      '280',
      '0',
      '281',
      '0',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'TABLES',
      '0',
      'TABLE',
      '2',
      'LTYPE',
      '0',
      'LTYPE',
      '5',
      '14',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbLinetypeTableRecord',
      '2',
      'DASHED',
      '70',
      '0',
      '3',
      'Dashed __ __',
      '72',
      '65',
      '73',
      '2',
      '40',
      '0.75',
      '49',
      '0.5',
      '74',
      '0',
      '49',
      '-0.25',
      '74',
      '0',
      '0',
      'ENDTAB',
      '0',
      'TABLE',
      '2',
      'STYLE',
      '0',
      'STYLE',
      '5',
      '15',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbTextStyleTableRecord',
      '2',
      'Notes',
      '70',
      '0',
      '40',
      '2.5',
      '41',
      '1',
      '50',
      '0',
      '71',
      '0',
      '42',
      '2.5',
      '3',
      'Arial.ttf',
      '4',
      '',
      '0',
      'ENDTAB',
      '0',
      'TABLE',
      '2',
      'DIMSTYLE',
      '0',
      'DIMSTYLE',
      '5',
      '16',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbDimStyleTableRecord',
      '2',
      'MyDim',
      '70',
      '0',
      '3',
      '<>',
      '40',
      '1',
      '41',
      '0.18',
      '140',
      '0.18',
      '147',
      '0.09',
      '71',
      '0',
      '170',
      '0',
      '0',
      'ENDTAB',
      '0',
      'TABLE',
      '2',
      'VPORT',
      '0',
      'VPORT',
      '5',
      '17',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbViewportTableRecord',
      '2',
      '*Active',
      '10',
      '0',
      '20',
      '0',
      '11',
      '1',
      '21',
      '1',
      '12',
      '50',
      '22',
      '50',
      '40',
      '100',
      '41',
      '1.5',
      '42',
      '50',
      '70',
      '0',
      '72',
      '1000',
      '0',
      'ENDTAB',
      '0',
      'TABLE',
      '2',
      'BLOCK_RECORD',
      '0',
      'BLOCK_RECORD',
      '5',
      '1F',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*Model_Space',
      '70',
      '0',
      '280',
      '1',
      '281',
      '0',
      '0',
      'BLOCK_RECORD',
      '5',
      '20',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*Paper_Space',
      '70',
      '0',
      '280',
      '1',
      '281',
      '0',
      '0',
      'BLOCK_RECORD',
      '5',
      '21',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      'Door',
      '70',
      '4',
      '280',
      '1',
      '281',
      '0',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'BLOCKS',
      '0',
      'BLOCK',
      '5',
      '22',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockBegin',
      '2',
      'Door',
      '70',
      '0',
      '10',
      '1',
      '20',
      '2',
      '30',
      '0',
      '3',
      'Door',
      '0',
      'LINE',
      '5',
      '23',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbLine',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '10',
      '21',
      '0',
      '31',
      '0',
      '0',
      'ENDBLK',
      '5',
      '24',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockEnd',
      '0',
      'BLOCK',
      '5',
      '25',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockBegin',
      '2',
      'XRefBlock',
      '70',
      '0',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '3',
      'XRefBlock',
      '1',
      'C:\\refs\\other.dwg',
      '0',
      'ENDBLK',
      '5',
      '26',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockEnd',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    expect(db.classes).toHaveLength(1)
    expect(db.classes[0].name).toBe('ACDBDICTIONARYWDFLT')
    expect(db.classes[0].cppClassName).toBe('AcDbDictionaryWithDefault')

    const ltype = db.tables.linetypeTable.getAt('DASHED')
    expect(ltype).toBeDefined()
    expect(ltype!.comments).toBe('Dashed __ __')
    expect(ltype!.patternLength).toBeCloseTo(0.75)
    expect(ltype!.numDashes).toBe(2)

    const style = db.tables.textStyleTable.getAt('Notes')
    expect(style).toBeDefined()
    expect(style!.fileName).toBe('Arial')
    expect(style!.textSize).toBeCloseTo(2.5)

    const dim = db.tables.dimStyleTable.getAt('MyDim')
    expect(dim).toBeDefined()
    expect(dim!.dimpost).toBe('<>')
    expect(dim!.dimasz).toBeCloseTo(0.18)

    const vport = db.tables.viewportTable.getAt('*Active')
    expect(vport).toBeDefined()
    expect(vport!.center).toMatchObject({ x: 50, y: 50 })
    expect(vport!.gsView.viewHeight).toBeCloseTo(100)
    expect(vport!.gsView.aspectRatio).toBeCloseTo(1.5)
    expect(vport!.circleSides).toBe(1000)

    const door = db.tables.blockTable.getAt('Door')
    expect(door).toBeDefined()
    expect(door!.origin).toMatchObject({ x: 1, y: 2, z: 0 })
    expect(door!.blockInsertUnits).toBe(4)
    const doorEntities = [...door!.newIterator()]
    expect(doorEntities).toHaveLength(1)
    expect(doorEntities[0]).toBeInstanceOf(AcDbLine)

    const xref = db.tables.blockTable.getAt('XRefBlock')
    expect(xref).toBeDefined()
    expect(xref!.pathName).toBe('C:\\refs\\other.dwg')
    expect(xref!.flags & AcDbBlockTableRecordFlag.Xref).toBeTruthy()
    expect(xref!.isUnresolvedXref).toBe(true)
  })

  it('treats AutoCAD Resolved xref blocks (flag 36) as unresolved', async () => {
    // Matches attached xrefs written by AutoCAD: empty BLOCK, path on code 1,
    // flags = Xref|Resolved (36). Geometry is not bound into the host file.
    const dxf = [
      '0',
      'SECTION',
      '2',
      'BLOCKS',
      '0',
      'BLOCK',
      '5',
      '298',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockBegin',
      '2',
      'xref1',
      '70',
      '36',
      '10',
      '0.0',
      '20',
      '0.0',
      '30',
      '0.0',
      '3',
      'xref1',
      '1',
      '.\\xref1.dwg',
      '0',
      'ENDBLK',
      '5',
      '299',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockEnd',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    const xref = db.tables.blockTable.getAt('xref1')
    expect(xref).toBeDefined()
    expect(xref!.pathName).toBe('.\\xref1.dwg')
    expect(xref!.isXref).toBe(true)
    expect(xref!.flags & AcDbBlockTableRecordFlag.Resolved).toBe(0)
    expect(xref!.isUnresolvedXref).toBe(true)
    expect(db.tables.blockTable.getUnresolvedXrefs().map(b => b.name)).toEqual([
      'xref1'
    ])
  })

  it('streams OBJECTS layouts, imagedefs, styles, and ATTRIB→INSERT linking', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'HEADER',
      '9',
      '$ACADVER',
      '1',
      'AC1032',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'TABLES',
      '0',
      'TABLE',
      '2',
      'BLOCK_RECORD',
      '0',
      'BLOCK_RECORD',
      '5',
      '1F',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*Model_Space',
      '0',
      'BLOCK_RECORD',
      '5',
      '20',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*Paper_Space',
      '340',
      'A1',
      '0',
      'BLOCK_RECORD',
      '5',
      '21',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      'Title',
      '0',
      'ENDTAB',
      '0',
      'TABLE',
      '2',
      'STYLE',
      '0',
      'STYLE',
      '5',
      '30',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbTextStyleTableRecord',
      '2',
      'Notes',
      '70',
      '0',
      '40',
      '0',
      '41',
      '1',
      '50',
      '0',
      '71',
      '0',
      '42',
      '2.5',
      '3',
      'Arial',
      '4',
      '',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      'INSERT',
      '5',
      '50',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockReference',
      '2',
      'Title',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '0',
      'ATTRIB',
      '5',
      '51',
      '330',
      '50',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbText',
      '10',
      '1',
      '20',
      '1',
      '30',
      '0',
      '40',
      '2.5',
      '1',
      'REV-A',
      '7',
      'Notes',
      '100',
      'AcDbAttribute',
      '2',
      'REV',
      '70',
      '0',
      '0',
      'TEXT',
      '5',
      '52',
      '330',
      '20',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '67',
      '1',
      '100',
      'AcDbText',
      '10',
      '10',
      '20',
      '10',
      '30',
      '0',
      '40',
      '3',
      '1',
      'Paper Text',
      '7',
      'Notes',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'OBJECTS',
      '0',
      'LAYOUT',
      '5',
      'A0',
      '330',
      'D',
      '100',
      'AcDbPlotSettings',
      '1',
      '',
      '2',
      'none',
      '4',
      'Letter',
      '6',
      '',
      '40',
      '0',
      '41',
      '0',
      '42',
      '0',
      '43',
      '0',
      '44',
      '215.9',
      '45',
      '279.4',
      '46',
      '0',
      '47',
      '0',
      '48',
      '0',
      '49',
      '0',
      '140',
      '0',
      '141',
      '0',
      '142',
      '1',
      '143',
      '1',
      '70',
      '1024',
      '72',
      '1',
      '73',
      '0',
      '74',
      '0',
      '7',
      '',
      '75',
      '0',
      '100',
      'AcDbLayout',
      '1',
      'Model',
      '70',
      '1',
      '71',
      '0',
      '10',
      '0',
      '20',
      '0',
      '11',
      '12',
      '21',
      '9',
      '12',
      '0',
      '22',
      '0',
      '32',
      '0',
      '14',
      '0',
      '24',
      '0',
      '34',
      '0',
      '15',
      '0',
      '25',
      '0',
      '35',
      '0',
      '146',
      '0',
      '13',
      '0',
      '23',
      '0',
      '33',
      '0',
      '16',
      '1',
      '26',
      '0',
      '36',
      '0',
      '17',
      '0',
      '27',
      '1',
      '37',
      '0',
      '76',
      '0',
      '330',
      '1F',
      '0',
      'LAYOUT',
      '5',
      'A1',
      '330',
      'D',
      '100',
      'AcDbPlotSettings',
      '1',
      '',
      '2',
      'none',
      '4',
      'Letter',
      '6',
      '',
      '40',
      '0.25',
      '41',
      '0.25',
      '42',
      '0.25',
      '43',
      '0.25',
      '44',
      '215.9',
      '45',
      '279.4',
      '46',
      '0',
      '47',
      '0',
      '48',
      '0',
      '49',
      '0',
      '140',
      '0',
      '141',
      '0',
      '142',
      '1',
      '143',
      '1',
      '70',
      '0',
      '72',
      '0',
      '73',
      '0',
      '74',
      '5',
      '7',
      '',
      '75',
      '16',
      '100',
      'AcDbLayout',
      '1',
      'Layout1',
      '70',
      '1',
      '71',
      '1',
      '10',
      '0',
      '20',
      '0',
      '11',
      '12',
      '21',
      '9',
      '330',
      '20',
      '0',
      'IMAGEDEF',
      '5',
      'B0',
      '100',
      'AcDbRasterImageDef',
      '1',
      'C:\\images\\site.png',
      '280',
      '1',
      '281',
      '0',
      '0',
      'LAYER_FILTER',
      '5',
      'B1',
      '100',
      'AcDbFilter',
      '100',
      'AcDbLayerFilter',
      '8',
      'Walls',
      '8',
      'Doors',
      '0',
      'LAYER_INDEX',
      '5',
      'B2',
      '100',
      'AcDbIndex',
      '40',
      '2451545.0',
      '100',
      'AcDbLayerIndex',
      '8',
      '0',
      '360',
      'C0',
      '90',
      '3',
      '0',
      'MLINESTYLE',
      '5',
      'B3',
      '100',
      'AcDbMlineStyle',
      '2',
      'Standard',
      '70',
      '0',
      '3',
      '',
      '62',
      '256',
      '51',
      '90',
      '52',
      '90',
      '71',
      '2',
      '49',
      '0.5',
      '62',
      '2',
      '6',
      'BYLAYER',
      '49',
      '-0.5',
      '62',
      '3',
      '6',
      'BYLAYER',
      '0',
      'MLEADERSTYLE',
      '5',
      'B4',
      '100',
      'AcDbMLeaderStyle',
      '179',
      '2',
      '170',
      '2',
      '171',
      '1',
      '172',
      '0',
      '90',
      '2',
      '40',
      '0',
      '41',
      '0',
      '173',
      '1',
      '91',
      '-1056964608',
      '340',
      '0',
      '92',
      '-2',
      '290',
      '1',
      '42',
      '2',
      '291',
      '1',
      '43',
      '8',
      '3',
      'Default',
      '44',
      '4',
      '300',
      '',
      '45',
      '4',
      '0',
      'DICTIONARY',
      '5',
      'D0',
      '100',
      'AcDbDictionary',
      '281',
      '1',
      '3',
      'ACAD_LAYERFILTERS',
      '350',
      'D1',
      '0',
      'DICTIONARY',
      '5',
      'D1',
      '100',
      'AcDbDictionary',
      '281',
      '1',
      '3',
      'WallsOnly',
      '350',
      'XR1',
      '0',
      'XRECORD',
      '5',
      'XR1',
      '100',
      'AcDbXrecord',
      '280',
      '1',
      '1',
      'WallsOnly',
      '1',
      'NAME==\"Walls\"',
      '1',
      '*',
      '1',
      '*',
      '70',
      '0',
      '1',
      '',
      '1',
      '',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    const modelLayout = db.objects.layout.getAt('Model')
    expect(modelLayout).toBeDefined()
    expect(modelLayout!.blockTableRecordId).toBe(
      db.tables.blockTable.modelSpace.objectId
    )
    expect(modelLayout!.modelType).toBe(true)

    const layout1 = db.objects.layout.getAt('Layout1')
    expect(layout1).toBeDefined()
    expect(layout1!.tabOrder).toBe(1)
    expect(layout1!.blockTableRecordId).toBe('20')
    expect(db.tables.blockTable.getAt('*Paper_Space')!.layoutId).toBe('A1')

    const imageDef = db.objects.imageDefinition.getAt('B0')
    expect(imageDef).toBeDefined()
    expect(imageDef!.sourceFileName).toBe('C:\\images\\site.png')

    const layerFilter = db.objects.layerFilter.getAt('B1')
    expect(layerFilter).toBeDefined()
    expect([...layerFilter!.layerNames]).toEqual(['Walls', 'Doors'])

    const layerIndex = db.objects.layerIndex.getAt('B2')
    expect(layerIndex).toBeDefined()
    expect(layerIndex!.lastUpdatedAt).toBeCloseTo(2451545.0)
    expect([...layerIndex!.layerNames]).toEqual(['0'])

    const mline = db.objects.mlineStyle.getAt('Standard')
    expect(mline).toBeDefined()
    expect(mline!.elementCount).toBe(2)

    const mleader = db.objects.mleaderStyle.getAt('B4')
    expect(mleader).toBeDefined()
    expect(mleader!.description).toBe('Default')
    expect(mleader!.maxLeaderSegmentsPoints).toBe(2)

    expect(db.layerFilters.root.getNestedFilters().length).toBeGreaterThan(0)
    expect(db.layerFilters.root.getNestedFilters()[0].name).toBe('WallsOnly')

    const inserts = [...db.tables.blockTable.modelSpace.newIterator()].filter(
      e => e instanceof AcDbBlockReference
    ) as AcDbBlockReference[]
    expect(inserts).toHaveLength(1)
    const attribs = [...inserts[0].attributeIterator()]
    expect(attribs).toHaveLength(1)
    expect(attribs[0].tag).toBe('REV')
    expect(attribs[0].textString).toBe('REV-A')

    const paper = db.tables.blockTable.getAt('*Paper_Space')!
    const paperEntities = [...paper.newIterator()]
    expect(paperEntities.some(e => e instanceof AcDbText)).toBe(true)
  })

  it('parses TEXT, MTEXT, DIMENSION, and ACAD_TABLE with real-world extras', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'HEADER',
      '9',
      '$ACADVER',
      '1',
      'AC1032',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'TABLES',
      '0',
      'TABLE',
      '2',
      'BLOCK_RECORD',
      '0',
      'BLOCK_RECORD',
      '5',
      '1F',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*Model_Space',
      '0',
      'BLOCK_RECORD',
      '5',
      '20',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*D1',
      '0',
      'BLOCK_RECORD',
      '5',
      '21',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbBlockTableRecord',
      '2',
      '*T1',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'BLOCKS',
      '0',
      'BLOCK',
      '5',
      '30',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockBegin',
      '2',
      '*Model_Space',
      '70',
      '0',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '0',
      'ENDBLK',
      '5',
      '31',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockEnd',
      '0',
      'BLOCK',
      '5',
      '32',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockBegin',
      '2',
      '*D1',
      '70',
      '1',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '0',
      'LINE',
      '5',
      '33',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbLine',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '10',
      '21',
      '0',
      '31',
      '0',
      '0',
      'MTEXT',
      '5',
      '34',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbMText',
      '10',
      '5',
      '20',
      '1',
      '30',
      '0',
      '40',
      '2.5',
      '41',
      '10',
      '71',
      '5',
      '1',
      '16',
      '210',
      '0',
      '220',
      '0',
      '230',
      '1',
      '0',
      'ENDBLK',
      '5',
      '35',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockEnd',
      '0',
      'BLOCK',
      '5',
      '36',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockBegin',
      '2',
      '*T1',
      '70',
      '1',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '0',
      'TEXT',
      '5',
      '37',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbText',
      '10',
      '1',
      '20',
      '1',
      '30',
      '0',
      '40',
      '2',
      '1',
      'CellA',
      '100',
      'AcDbText',
      '73',
      '2',
      '0',
      'ENDBLK',
      '5',
      '38',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockEnd',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      // TEXT with layout tab name + dual AcDbText subclass (group 73 after 100)
      '0',
      'TEXT',
      '5',
      '40',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '410',
      'Model',
      '100',
      'AcDbText',
      '10',
      '100',
      '20',
      '100',
      '30',
      '0',
      '40',
      '3',
      '1',
      'Title',
      '50',
      '0',
      '7',
      'Standard',
      '71',
      '0',
      '72',
      '1',
      '11',
      '105',
      '21',
      '100',
      '31',
      '0',
      '210',
      '0',
      '220',
      '0',
      '230',
      '1',
      '100',
      'AcDbText',
      '73',
      '2',
      // MTEXT with extrusion after content
      '0',
      'MTEXT',
      '5',
      '41',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '410',
      'Model',
      '100',
      'AcDbMText',
      '10',
      '0',
      '20',
      '50',
      '30',
      '0',
      '40',
      '2.5',
      '41',
      '40',
      '71',
      '1',
      '1',
      'Notes line',
      '3',
      ' continued',
      '7',
      'Standard',
      '210',
      '0',
      '220',
      '0',
      '230',
      '1',
      '11',
      '1',
      '21',
      '0',
      '31',
      '0',
      // Rotated DIMENSION with group 51 + anonymous block
      '0',
      'DIMENSION',
      '5',
      '42',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '410',
      'Model',
      '100',
      'AcDbDimension',
      '2',
      '*D1',
      '10',
      '20',
      '20',
      '0',
      '30',
      '0',
      '11',
      '15',
      '21',
      '2',
      '31',
      '0',
      '70',
      '0',
      '1',
      '<>',
      '51',
      '0',
      '3',
      'Standard',
      '100',
      'AcDbRotatedDimension',
      '12',
      '20',
      '22',
      '0',
      '32',
      '0',
      '13',
      '0',
      '23',
      '0',
      '33',
      '0',
      '14',
      '20',
      '24',
      '0',
      '34',
      '0',
      '50',
      '0',
      // ACAD_TABLE referencing anonymous block *T1
      '0',
      'ACAD_TABLE',
      '5',
      '43',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '410',
      'Model',
      '100',
      'AcDbBlockReference',
      '2',
      '*T1',
      '10',
      '200',
      '20',
      '200',
      '30',
      '0',
      '100',
      'AcDbTable',
      '280',
      '0',
      '11',
      '1',
      '21',
      '0',
      '31',
      '0',
      '91',
      '2',
      '92',
      '2',
      '141',
      '5',
      '141',
      '5',
      '142',
      '20',
      '142',
      '20',
      '171',
      '1',
      '172',
      '0',
      '173',
      '0',
      '174',
      '0',
      '175',
      '1',
      '176',
      '1',
      '1',
      'Item',
      '170',
      '5',
      '171',
      '1',
      '172',
      '0',
      '173',
      '0',
      '174',
      '0',
      '175',
      '1',
      '176',
      '1',
      '301',
      'CELL_VALUE',
      '90',
      '4',
      '302',
      'Value',
      '304',
      'ACVALUE_END',
      '170',
      '5',
      '171',
      '1',
      '1',
      'R2C1',
      '171',
      '1',
      '1',
      'R2C2',
      '0',
      'ENDSEC',
      '0',
      'EOF'
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    const model = [...db.tables.blockTable.modelSpace.newIterator()]
    const text = model.find(e => e instanceof AcDbText) as AcDbText | undefined
    expect(text).toBeDefined()
    expect(text!.textString).toBe('Title')
    expect(text!.height).toBeCloseTo(3)
    expect(text!.horizontalMode).toBe(1)
    expect(text!.verticalMode).toBe(2)
    expect(text!.alignmentPoint.x).toBeCloseTo(105)

    const mtext = model.find(e => e instanceof AcDbMText) as AcDbMText | undefined
    expect(mtext).toBeDefined()
    expect(mtext!.contents).toBe('Notes line continued')
    expect(mtext!.direction.x).toBeCloseTo(1)

    const dim = model.find(
      e => e instanceof AcDbRotatedDimension
    ) as AcDbRotatedDimension | undefined
    expect(dim).toBeDefined()
    expect(dim!.dimBlockId).toBe('*D1')
    expect(dim!.xLine1Point.x).toBeCloseTo(0)
    expect(dim!.xLine2Point.x).toBeCloseTo(20)
    expect(dim!.dimLinePoint.x).toBeCloseTo(20)
    // Group 12 sets dim block insert; group 10 must not (avoids double-offset).
    expect(dim!.dimBlockPosition.x).toBeCloseTo(20)
    expect(dim!.dimBlockPosition.y).toBeCloseTo(0)

    const table = model.find(e => e instanceof AcDbTable) as AcDbTable | undefined
    expect(table).toBeDefined()
    expect(table!.blockName).toBe('*T1')
    expect(table!.numRows).toBe(2)
    expect(table!.numColumns).toBe(2)
    expect(table!.cell(0)?.text).toBe('Item')
    expect(table!.cell(1)?.text).toBe('Value')
    // Table-level flags must not be overwritten by CELL_VALUE metadata (90).
    expect(table!.tableValueFlag ?? 0).not.toBe(4)

    const dimBlock = db.tables.blockTable.getAt('*D1')!
    const dimBlockMtext = [...dimBlock.newIterator()].find(
      e => e instanceof AcDbMText
    ) as AcDbMText | undefined
    expect(dimBlockMtext?.contents).toBe('16')

    const tableBlock = db.tables.blockTable.getAt('*T1')!
    const tableBlockText = [...tableBlock.newIterator()].find(
      e => e instanceof AcDbText
    ) as AcDbText | undefined
    expect(tableBlockText?.textString).toBe('CellA')
    expect(tableBlockText?.verticalMode).toBe(2)
  })

  it('keeps dimBlockPosition at origin when DIMENSION has no group 12', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      'DIMENSION',
      '5',
      '42',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbDimension',
      '2',
      '*D1',
      '10',
      '1039.68',
      '20',
      '-324.2',
      '30',
      '0',
      '11',
      '1055.68',
      '21',
      '-321.33',
      '31',
      '0',
      '70',
      '32',
      '3',
      'Standard',
      '100',
      'AcDbAlignedDimension',
      '13',
      '1071.68',
      '23',
      '-315.43',
      '33',
      '0',
      '14',
      '1039.68',
      '24',
      '-315.43',
      '34',
      '0',
      '100',
      'AcDbRotatedDimension',
      '0',
      'ENDSEC',
      '0',
      'EOF'
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    const dim = [...db.tables.blockTable.modelSpace.newIterator()].find(
      e => e instanceof AcDbRotatedDimension
    ) as AcDbRotatedDimension | undefined

    expect(dim).toBeDefined()
    expect(dim!.dimLinePoint.x).toBeCloseTo(1039.68)
    expect(dim!.dimLinePoint.y).toBeCloseTo(-324.2)
    // Without group 12, anonymous *D* block must stay untranslated.
    expect(dim!.dimBlockPosition.x).toBeCloseTo(0)
    expect(dim!.dimBlockPosition.y).toBeCloseTo(0)
    expect(dim!.dimBlockPosition.z).toBeCloseTo(0)
  })

  it('suppresses entityAppended until ENTITY flush after PARSE', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'TABLES',
      '0',
      'TABLE',
      '2',
      'STYLE',
      '0',
      'STYLE',
      '5',
      '61',
      '100',
      'AcDbSymbolTableRecord',
      '100',
      'AcDbTextStyleTableRecord',
      '2',
      '标准',
      '70',
      '0',
      '40',
      '0.0',
      '41',
      '1.0',
      '50',
      '0.0',
      '71',
      '0',
      '42',
      '0.2',
      '3',
      '',
      '4',
      '',
      '1001',
      'ACAD',
      '1000',
      'SimSun',
      '1071',
      '0',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      'MTEXT',
      '5',
      '100',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbMText',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '40',
      '2.5',
      '1',
      'Hello',
      '7',
      '标准',
      '0',
      'ENDSEC',
      '0',
      'EOF'
    ].join('\n')

    const stages: string[] = []
    let appendedDuringParse = false
    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db
    db.events.entityAppended.addEventListener(() => {
      // During PARSE the batch must still be open.
      if (!stages.includes('PARSE:END')) {
        appendedDuringParse = true
      }
    })

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, {
      minimumChunkSize: 50,
      progress: async (_pct, stage, status) => {
        stages.push(`${stage}:${status}`)
      }
    })

    expect(stages.filter(s => !s.endsWith(':IN-PROGRESS'))).toEqual([
      'START:START',
      'PARSE:START',
      'PARSE:END',
      'ENTITY:START',
      'ENTITY:END',
      'END:END'
    ])
    expect(appendedDuringParse).toBe(false)

    const style = db.tables.textStyleTable.getAt('标准')
    expect(style?.fileName).toBe('SimSun')
  })

  it('emits PARSE IN-PROGRESS while streaming entities', async () => {
    const lines = [
      '0',
      'SECTION',
      '2',
      'ENTITIES'
    ]
    for (let i = 0; i < 40; i++) {
      lines.push(
        '0',
        'LINE',
        '5',
        (0x100 + i).toString(16).toUpperCase(),
        '100',
        'AcDbEntity',
        '8',
        '0',
        '100',
        'AcDbLine',
        '10',
        String(i),
        '20',
        '0',
        '30',
        '0',
        '11',
        String(i + 1),
        '20',
        '1',
        '30',
        '0'
      )
    }
    lines.push('0', 'ENDSEC', '0', 'EOF')

    const stages: string[] = []
    const percentages: number[] = []
    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(lines.join('\n')).buffer
    await converter.read(buffer, db, { minimumChunkSize: 5, progress: async (pct, stage, status) => {
      stages.push(`${stage}:${status}`)
      percentages.push(pct)
    }})

    expect(stages).toContain('PARSE:IN-PROGRESS')
    expect(stages).toContain('ENTITY:IN-PROGRESS')
    expect(stages.filter(s => !s.endsWith(':IN-PROGRESS'))).toEqual([
      'START:START',
      'PARSE:START',
      'PARSE:END',
      'ENTITY:START',
      'ENTITY:END',
      'END:END'
    ])
    const parseProgressPcts = percentages.filter(
      (_, i) => stages[i] === 'PARSE:IN-PROGRESS'
    )
    expect(parseProgressPcts.length).toBeGreaterThan(0)
    for (const pct of parseProgressPcts) {
      expect(pct).toBeLessThan(18)
    }
    for (let i = 1; i < parseProgressPcts.length; i++) {
      expect(parseProgressPcts[i]!).toBeGreaterThanOrEqual(parseProgressPcts[i - 1]!)
    }
    const entityProgressPcts = percentages.filter(
      (_, i) => stages[i] === 'ENTITY:IN-PROGRESS'
    )
    expect(entityProgressPcts.length).toBeGreaterThan(0)
    expect(entityProgressPcts[0]!).toBeGreaterThanOrEqual(20)
    expect(entityProgressPcts[entityProgressPcts.length - 1]!).toBeLessThanOrEqual(98)
  })

  it('does not count SEQEND as an unknown entity', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      'INSERT',
      '5',
      '50',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbBlockReference',
      '2',
      'Title',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '0',
      'ATTRIB',
      '5',
      '51',
      '330',
      '50',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbText',
      '10',
      '1',
      '20',
      '1',
      '30',
      '0',
      '40',
      '2.5',
      '1',
      'REV-A',
      '100',
      'AcDbAttribute',
      '2',
      'REV',
      '70',
      '0',
      '0',
      'SEQEND',
      '5',
      '52',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    const inserts = [...db.tables.blockTable.modelSpace.newIterator()].filter(
      e => e instanceof AcDbBlockReference
    ) as AcDbBlockReference[]
    expect(inserts).toHaveLength(1)
    expect([...inserts[0].attributeIterator()]).toHaveLength(1)

    // Re-read via document reader to assert the diagnostic counter.
    const { AcDbDxfDocumentReader } = await import('../src/dxf/AcDbDxfDocumentReader')
    const { AcDbDxfFiler } = await import('../src/base/AcDbDxfFiler')
    const db2 = new AcDbDatabase()
    db2.createDefaultData()
    const reader = new AcDbDxfDocumentReader(db2)
    const result = await reader.read(AcDbDxfFiler.fromString(dxf))
    expect(result.unknownEntityCount).toBe(0)
  })

  it('skips paper-space entities inside BLOCKS to avoid ENTITIES duplicates', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'TABLES',
      '0',
      'TABLE',
      '2',
      'BLOCK_RECORD',
      '0',
      'BLOCK_RECORD',
      '5',
      '1F',
      '2',
      '*Model_Space',
      '0',
      'BLOCK_RECORD',
      '5',
      '20',
      '2',
      '*Paper_Space',
      '0',
      'ENDTAB',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'BLOCKS',
      '0',
      'BLOCK',
      '5',
      'B1',
      '2',
      '*Paper_Space',
      '70',
      '0',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '0',
      'LINE',
      '5',
      'B2',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbLine',
      '10',
      '0',
      '20',
      '0',
      '30',
      '0',
      '11',
      '1',
      '21',
      '0',
      '31',
      '0',
      '0',
      'ENDBLK',
      '5',
      'B3',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      'LINE',
      '5',
      'E1',
      '330',
      '20',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '67',
      '1',
      '100',
      'AcDbLine',
      '10',
      '10',
      '20',
      '10',
      '30',
      '0',
      '11',
      '11',
      '21',
      '10',
      '31',
      '0',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const db = new AcDbDatabase()
    db.createDefaultData()
    acdbHostApplicationServices().workingDatabase = db

    const converter = new AcDbNativeDxfConverter()
    const buffer = new TextEncoder().encode(dxf).buffer
    await converter.read(buffer, db, { minimumChunkSize: 50 })

    const paper = db.tables.blockTable.getAt('*Paper_Space')!
    const lines = [...paper.newIterator()].filter(e => e instanceof AcDbLine)
    // Only the ENTITIES-section line (handle E1), not the BLOCKS duplicate.
    expect(lines).toHaveLength(1)
    expect(lines[0].objectId.toUpperCase()).toBe('E1')
  })

  it('counts unknown OBJECTS types without aborting the section', async () => {
    const dxf = [
      '0',
      'SECTION',
      '2',
      'OBJECTS',
      '0',
      'ACDBPLACEHOLDER',
      '5',
      'AA',
      '100',
      'AcDbPlaceHolder',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const { AcDbDxfDocumentReader } = await import('../src/dxf/AcDbDxfDocumentReader')
    const { AcDbDxfFiler } = await import('../src/base/AcDbDxfFiler')
    const db = new AcDbDatabase()
    db.createDefaultData()
    const reader = new AcDbDxfDocumentReader(db)
    const result = await reader.read(AcDbDxfFiler.fromString(dxf))
    expect(result.unknownObjectCount).toBe(1)
    expect(result.unknownEntityCount).toBe(0)
  })

  it('attaches ACDSDATA ASM_Data SAB bytes to matching 3DSOLID entities', async () => {
    // Hex for ASCII "ACIS BinaryFile...." — enough to verify ownership wiring.
    const sabHex = '414349532042696E61727946696C65'
    const dxf = [
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      '3DSOLID',
      '5',
      '7E9',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbModelerGeometry',
      '290',
      '0',
      '2',
      '{00000000-0000-0000-0000-000000000000}',
      '100',
      'AcDb3dSolid',
      '350',
      '100',
      '0',
      'ENDSEC',
      '0',
      'SECTION',
      '2',
      'ACDSDATA',
      '0',
      'ACDSRECORD',
      '320',
      '7E9',
      '2',
      'ASM_Data',
      '310',
      sabHex,
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const converter = new AcDbNativeDxfConverter()
    const db = new AcDbDatabase()
    acdbHostApplicationServices().workingDatabase = db
    await converter.read(new TextEncoder().encode(dxf).buffer, db, { minimumChunkSize: 50 })

    const solids = [...db.tables.blockTable.modelSpace.newIterator()].filter(
      e => e instanceof AcDb3dSolid
    )
    expect(solids).toHaveLength(1)
    const solid = solids[0] as AcDb3dSolid
    expect(solid.historyObjectSoftId).toBe('100')
    expect(solid.guid).toBe('{00000000-0000-0000-0000-000000000000}')
    expect(solid.sabBytes).toBeDefined()
    expect(String.fromCharCode(...solid.sabBytes!.subarray(0, 4))).toBe('ACIS')
  })

  it('decrypts obfuscated inline ACIS SAT groups 1/3 on 3DSOLID', async () => {
    const { acdbDecryptAcisData } = await import('../src/acis')
    const plain = 'point $-1 1 2 3 #'
    const encrypted = acdbDecryptAcisData(plain) // involution
    const dxf = [
      '0',
      'SECTION',
      '2',
      'ENTITIES',
      '0',
      '3DSOLID',
      '5',
      'A1',
      '100',
      'AcDbEntity',
      '8',
      '0',
      '100',
      'AcDbModelerGeometry',
      '70',
      '400',
      '1',
      encrypted,
      '100',
      'AcDb3dSolid',
      '0',
      'ENDSEC',
      '0',
      'EOF',
      ''
    ].join('\n')

    const converter = new AcDbNativeDxfConverter()
    const db = new AcDbDatabase()
    acdbHostApplicationServices().workingDatabase = db
    await converter.read(new TextEncoder().encode(dxf).buffer, db, { minimumChunkSize: 50 })

    const solid = [...db.tables.blockTable.modelSpace.newIterator()].find(
      e => e instanceof AcDb3dSolid
    ) as AcDb3dSolid
    expect(solid).toBeDefined()
    expect(solid.version).toBe(400)
    expect(solid.acisData).toContain('point $-1 1 2 3')
    expect(solid.hasRenderableGeometry).toBe(true)
  })
})
