# Workflow for publishing packages
name: publish

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  actions: read
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org
       
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build javascript api package
        run: pnpm build

      - name: Publish packages to npm
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
